name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install

      - name: Setup Database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Rubocop
        run: bundle exec rubocop
      
      - name: minitest
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY  }}
        run: bundle exec rails test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy in Amazon EC2 Main
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /var/www/rails/realworld_api &&
            git fetch --all &&
            git reset --hard origin/main &&
            bundle install &&
            bundle exec rails db:migrate RAILS_ENV=production &&
            if [[ -e tmp/pids/puma.pid ]];then kill $(cat tmp/pids/puma.pid); echo kill puma process;fi &&
            screen -dm bundle exec rails s -e production
            '

      - name: Deploy in Amazon EC2 Sub
        env:
          PRIVATE_KEY_SUB: ${{ secrets.AWS_PRIVATE_KEY_SUB  }}
          HOSTNAME_SUB : ${{ secrets.HOSTNAME_SUB  }}
          USER_NAME_SUB : ${{ secrets.USER_NAME_SUB  }}

        run: |
          echo "$PRIVATE_KEY_SUB" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME_SUB}@${HOSTNAME_SUB} '
            cd /var/www/rails/realworld_api &&
            git fetch --all &&
            git reset --hard origin/main &&
            bundle install &&
            bundle exec rails db:migrate RAILS_ENV=production &&
            if [[ -e tmp/pids/puma.pid ]];then kill $(cat tmp/pids/puma.pid); echo kill puma process;fi &&
            screen -dm bundle exec rails s -e production
            '